-- 课程知识图谱社区系统 - MySQL 建表脚本
CREATE DATABASE IF NOT EXISTS course_kg DEFAULT CHARSET utf8mb4;
USE course_kg;

CREATE TABLE users (id INT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(50) UNIQUE NOT NULL, password_hash VARCHAR(256) NOT NULL, display_name VARCHAR(100) DEFAULT '', avatar MEDIUMTEXT, title VARCHAR(50) DEFAULT '学徒', total_credits FLOAT DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE courses (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(200) NOT NULL, name_en VARCHAR(200) DEFAULT '', credit FLOAT DEFAULT 0, clc_number VARCHAR(50) DEFAULT '', category VARCHAR(50) DEFAULT '', department VARCHAR(100) DEFAULT '', description TEXT, teacher VARCHAR(100) DEFAULT '', exam_difficulty FLOAT DEFAULT 0, workload FLOAT DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE knowledge_points (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(200) NOT NULL, description TEXT, subject_category VARCHAR(100) DEFAULT '', dimension VARCHAR(50) DEFAULT '', difficulty INT DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE course_knowledge (id INT PRIMARY KEY AUTO_INCREMENT, course_id INT NOT NULL, kp_id INT NOT NULL, importance VARCHAR(20) DEFAULT 'medium', FOREIGN KEY (course_id) REFERENCES courses(id), FOREIGN KEY (kp_id) REFERENCES knowledge_points(id));

CREATE TABLE course_prerequisites (id INT PRIMARY KEY AUTO_INCREMENT, course_id INT NOT NULL, prereq_id INT NOT NULL, reason VARCHAR(255) DEFAULT '', FOREIGN KEY (course_id) REFERENCES courses(id), FOREIGN KEY (prereq_id) REFERENCES courses(id));

CREATE TABLE course_tags (id INT PRIMARY KEY AUTO_INCREMENT, course_id INT NOT NULL, tag VARCHAR(50) NOT NULL, count INT DEFAULT 1, FOREIGN KEY (course_id) REFERENCES courses(id));

CREATE TABLE ratings (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, course_id INT NOT NULL, score INT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (course_id) REFERENCES courses(id));

CREATE TABLE multi_dim_ratings (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, course_id INT NOT NULL, exam_difficulty INT DEFAULT 3, workload INT DEFAULT 3, practicality INT DEFAULT 3, career_help INT DEFAULT 3, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (course_id) REFERENCES courses(id));

CREATE TABLE reviews (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, course_id INT NOT NULL, content TEXT NOT NULL, is_pinned BOOLEAN DEFAULT FALSE, like_count INT DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (course_id) REFERENCES courses(id));

CREATE TABLE annotations (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, kp_id INT NOT NULL, content TEXT NOT NULL, is_private BOOLEAN DEFAULT FALSE, like_count INT DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (kp_id) REFERENCES knowledge_points(id));

CREATE TABLE questions (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, course_id INT NOT NULL, kp_id INT, title VARCHAR(200) NOT NULL, content TEXT, qtype VARCHAR(20) DEFAULT '选课咨询', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (course_id) REFERENCES courses(id));

CREATE TABLE answers (id INT PRIMARY KEY AUTO_INCREMENT, question_id INT NOT NULL, user_id INT NOT NULL, content TEXT NOT NULL, like_count INT DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (question_id) REFERENCES questions(id), FOREIGN KEY (user_id) REFERENCES users(id));

CREATE TABLE achievements (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT '', icon VARCHAR(50) DEFAULT 'book', condition_type VARCHAR(50), condition_value INT DEFAULT 1);

CREATE TABLE user_achievements (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, achievement_id INT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (achievement_id) REFERENCES achievements(id));

CREATE TABLE study_plans (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, name VARCHAR(100) DEFAULT '默认方案', semester VARCHAR(20), created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id));

CREATE TABLE study_plan_courses (id INT PRIMARY KEY AUTO_INCREMENT, plan_id INT NOT NULL, course_id INT NOT NULL, is_completed BOOLEAN DEFAULT FALSE, FOREIGN KEY (plan_id) REFERENCES study_plans(id), FOREIGN KEY (course_id) REFERENCES courses(id));

CREATE TABLE review_likes (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, review_id INT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (review_id) REFERENCES reviews(id));

CREATE TABLE annotation_likes (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, annotation_id INT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (annotation_id) REFERENCES annotations(id));

CREATE TABLE quiz_attempts (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, kp_id INT NOT NULL, correct BOOLEAN DEFAULT FALSE, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (kp_id) REFERENCES knowledge_points(id));
